version: '3'

services:
  oauth-stepup-demoapi-spring:
    build: ./oauth-stepup-demoapi-spring
    image: twogenidentity/oauth-stepup-demoapi-spring:latest
    container_name: oauth-stepup-demoapi-spring
    environment:
      OIDC_JWK_SET_URI: http://keycloak:8080/realms/bank/protocol/openid-connect/certs  
    ports:
      - 8001:8001
    depends_on:
      - keycloak  
  oidc-stepup-demobank-spa:
    build: ./oidc-stepup-demobank-spa
    image: twogenidentity/oidc-stepup-demobank-spa:latest
    container_name: oidc-stepup-demobank-spa
    environment:
      KC_URL: https://localhost
    ports:
      - 8000:8000
    depends_on:
      - keycloak      
  